theme = "lynx"
title = "Lynx"

enableEmoji = true
disableKinds = ["taxonomy", "term"]

[params.author]
  name = "The Mad hatter"
  headline = "A The Mad Hatter face painter home"
  image = "author.png"
  footer = ""
  links = [
    { link = { href = "https://m.me/annMarieTheMadHatter", text = "Messenger", icon = "messenger" } },
    { instagram = "https://www.instagram.com/the_mad___hatter/" },
    { facebook = "https://fb.com/annMarieTheMadHatter" },
  ]

[markup.highlight]
  noClasses = false

[markup.goldmark]
[markup.goldmark.renderer]
  unsafe = true

