theme = "lynx"
title = "The Mad Hatter"

enableEmoji = true
disableKinds = ["taxonomy", "term"]

[params.author]
  name = "The Mad hatter"
  headline = ""
  image = "author.png"
  footer = ""
  links = [
    { link = { href = "about/", text = "About me" } },
    { facebook-messenger = "https://m.me/annMarieTheMadHatter" },
    { instagram = "https://www.instagram.com/the_mad___hatter/" },
    { facebook = "https://fb.com/annMarieTheMadHatter" },
  ]

[markup.highlight]
  noClasses = false

[markup.goldmark]
[markup.goldmark.renderer]
  unsafe = true

